[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-audit --prefer-offline"]

[phases.build]
cmds = ["GENERATE_SOURCEMAP=false CI=false npm run build"]

[start]
cmd = "npx serve -s build -p $PORT"
