[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production --no-audit --prefer-offline"]

[phases.build]
cmds = ["echo 'Backend ready'"]

[start]
cmd = "node server.js"
